### ISSUE TITLE
P1 После нажатия кнопки создать, страница зависает.

### ISSUE THREAD

**Issue by LarinDim11** [gajet5/eap-marketplace#16]
Steps:
1. Ввести регистрационные данные, нажать кнопку создать 
Actual:
Страница зависает.

**Comment by LarinDim11** [comment]
Stop for testing

**Comment by gajet5** [comment]
Попробовал зарегистрировать аккаунт, регистрация прошла успешно, нужно посмотреть, что происходит у тебя @LarinDim11  на машине
